### ISSUE TITLE
too many arguments in call to httpclient.PostFile

### ISSUE THREAD

**Issue by Koenvh1** [bgpsecurity/rpstir2#15]
The build process is broken due to "too many arguments in call to httpclient.PostFile", probably caused by https://github.com/cpusoft/goutil/commit/e01c02468214c03e5e24d68c948f1c88c74dbc1b#diff-1fa60f3e000ad7ca2960248b0cd26aaafc439bfe1f12eda33dab756a08d0c60a

![afbeelding](https://user-images.githubusercontent.com/5168825/119369959-0a217780-bcb5-11eb-87ed-7c7866d81029.png)

**Comment by Koenvh1** [comment]
Any updates regarding this?

**Comment by cpusoft** [comment]
The new version of rpstir2 has been updated, and the bug has been fixed. Please download and recompile.
Thanks for finding the bug
